CREATE TABLE TBMFVERSAOSCRIPT (CDEMPRESA INTEGER NOT NULL,
CDMFVERSAOSCRIPT INTEGER NOT NULL,
CDMFVERSAO INTEGER NOT NULL,
SCRIPTSQL VARCHAR(800) NOT NULL 
, CONSTRAINT TBMFVERSAOSCRIPT_PK  PRIMARY KEY (CDEMPRESA,CDMFVERSAOSCRIPT  )
)
